### ISSUE TITLE
ローカル変数が宣言せずに使用されている

### ISSUE THREAD

**Issue by QBE256** [iroha-code/SRPGStudio_Plugin#1]
この部分、変数`i`を宣言せずに使用されているようです。
グローバル変数として設定されてしまうため、今後意図しないところで他のスクリプト等に影響を与えてしまう可能性があります。
お手すきの際に修正いただければと🙏
https://github.com/iroha-code/SRPGStudio_Plugin/blob/8bc89d61d60acf01ef9a7fde5eec42822d723b19/%E3%83%AC%E3%83%99%E3%83%AB%E3%82%A2%E3%83%83%E3%83%97%E7%94%BB%E9%9D%A2%EF%BC%9A%E8%A3%85%E5%82%99%E5%8F%AF%E8%83%BD%E7%86%9F%E7%B7%B4%E5%BA%A6%E3%81%AB%E5%88%B0%E9%81%94%E3%81%97%E3%81%9F%E6%AD%A6%E5%99%A8%E3%82%92%E8%A1%A8%E7%A4%BA/%E3%83%AC%E3%83%99%E3%83%AB%E3%82%A2%E3%83%83%E3%83%97%E7%94%BB%E9%9D%A2%EF%BC%9A%E8%A3%85%E5%82%99%E5%8F%AF%E8%83%BD%E7%86%9F%E7%B7%B4%E5%BA%A6%E3%81%AB%E5%88%B0%E9%81%94%E3%81%97%E3%81%9F%E6%AD%A6%E5%99%A8%E3%82%92%E8%A1%A8%E7%A4%BA.js#L83

**Comment by iroha-code** [comment]
早速ありがとうございます！修正しました。
